### ISSUE TITLE
Codereview

### ISSUE THREAD

**Issue by mounieju** [PolytechLyon/isi3-tp2-visiteur-jolivet-mounier-tp2#2]
Normalement nous avons tout fini, pouvez-vous nous faire des retours sur comment nous pouvons améliorer notre code s'il vous plaît?

**Comment by Slashgear** [comment]
- ⚠️ les packages en java par convention c'est en minuscule 

- 🔝 la gestion de la priorité

- 👍 le rapport

- Pouvez vous m'expliquer le cas d'utilisation du pattern visiteur ?

**Comment by natos33** [comment]
Merci de votre retour.

Dans notre cas, nous avons utilisé le design pattern visiteur car nous avions beaucoup d'opérations différentes à effectuer sur nos objets constituant l'arbre. Ainsi, le pattern visiteur nous a permis de rendre le code plus clair et plus propre

**Comment by Slashgear** [comment]
👌
